use_frameworks!
source 'https://github.com/ZkmlEasycarOrganization/ZkmlRemotePodSpecs.git'
# Cocoapods远程公共库
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'ZKMLLiuTools_Example' do
  pod 'ZKMLLiuTools', :path => '../'

  target 'ZKMLLiuTools_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
